### ISSUE TITLE
Update stats on the Nx Plugin Registry

### ISSUE THREAD

**Issue by isaacplmann** [jmcdo29/nx-uvu#14]
The Github Stars are not showing up for nx-uvu on the [Nx Plugin Registry](https://nx.dev/extending-nx/registry).

To fix this, you need to add a `repository.url` in the `package.json` that points to this repo.  i.e.

```json
{
  "repository": {
    "type": "git",
    "url": "https://github.com/nrwl/nx.git",
    "directory": "packages/web"
  }
}
```

Thanks,
Isaac (Nx Team)

**Comment by jmcdo29** [comment]
This just needs to be updated in GitHub or a new release as well, just want to make sure I post everything up as necessary

**Comment by isaacplmann** [comment]
It needs to be released before it will show up on the plugin registry
