### ISSUE TITLE
[FEATURE] How about to upgrade "release" pipeline ?)

### ISSUE THREAD

**Issue by Arkady-Skvortsov** [jmcdo29/nx-uvu#6]
Hi, @jmcdo29)); I had seen you'r instrument right now and I would to try it so soon(Maybe in Ecommerce or in Pet), but... It's tool for testing, right?

**Comment by jmcdo29** [comment]
I'm not sure what the question is here

**Comment by Arkady-Skvortsov** [comment]
It's tool for testing Nx environment, yes?

**Comment by jmcdo29** [comment]
[`uvu`](https://github.com/lukeed/uvu) is a very _very_ fast test runner. `nx-uvu` is a Nx executor for the uvu cli, similar to `@nrwl/jest` but managed by me and for the `uvu` library instead.
