### ISSUE TITLE
Add option to pass custom tsconfig.json path

### ISSUE THREAD

**Issue by edraven-dev** [jmcdo29/nx-uvu#8]
As title says, there is no option to provide custom tsconfig.json path at the moment.

**Comment by jmcdo29** [comment]
This would be for the `ts-node` option specifically, right? As `swc` will use the swcrc file. Just want to make sure I know the requirement properly before working on this

**Comment by edraven-dev** [comment]
Yes, it would affect `ts-node` only.

**Comment by jmcdo29** [comment]
Supported in 1.3.0. This totally flew off my radar. Apologies for that
